apiVersion: v1
kind: Service
metadata:
  labels:
    app: gop-fileserver
  name: gop-fs-service
  namespace: default
spec:
  ports:
  - nodePort: 31200
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gop-fileserver
  type: NodePort