apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: jekyll
  name: jekyll
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jekyll
  template:
    metadata:
      labels:
        run: jekyll
    spec:
      initContainers:
      - name: copy-jekyll-site
        image: kodekloud/jekyll
        command: [ "jekyll", "new", "/site" ]
        volumeMounts:
        - name: jekyll-site
          mountPath: /site
      containers:
      - image: kodekloud/jekyll-serve
        name: jekyll-serve
      volumes:
      - name: jekyll-site
        persistentVolumeClaim:
          claimName: jekyll-site